### ISSUE TITLE
Insert image

### ISSUE THREAD

**Issue by MarcelHekkert** [outflux3/InputfieldSimpleMDE#6]
Great to have a MarkDown editor for Processwire. A little fix I would propose is making the 'image' button open the Processwire mediaviewer instead (or add it as an alternative), and offcourse put in the right link/url when selected a picture.

On a sidenote: It might help others to let them know the still need a markdown(parsedown) parser to display the output.

**Comment by outflux3** [comment]
Thanks, yes the image thing has been discussed a few times on the forum, and there are some solutions; the media viewer wouldn't work because it is designed for ck editor, so designed to insert img markup. But if you look for the threads, there are modules that let you grab the markdown code for any image on the page...

thanks for the advice about adding the instructions for markdown parser, i will add that info to the readme

**Comment by MarcelHekkert** [comment]
Thanks for the quick reply and understood. You're welcome on the advice.Keep up the good work.
